### PR TITLE
NXBT-2597: Switch ubuntu mirror to the AWS one

### PR DESCRIPTION
**Pull request by mguillaume**

### CODE REVIEW

**Comment by nelsonsilva** [comment]
shouldn't we rely on apt mirror to automatically pick proper mirror ?
In theory something like this should work:
```
deb mirror://mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-backports main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse
```

**Comment by mguillaume** [comment]
> shouldn't we rely on apt mirror to automatically pick proper mirror ?
> In theory something like this should work:
> 
> ```
> deb mirror://mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse
> deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse
> deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-backports main restricted universe multiverse
> deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse
> ```

That's an option if that works, let me check it out...

**Comment by jcarsique** [comment]
Worth to look at mirrors.ubuntu.com/mirrors.txt within AWS, this is now an APT standard.

**Comment by mguillaume** [comment]
"mirrors.txt" solution tested on an AWS instance -> it's using mirrors outside of AWS

**Pull request merged**
